name: ci Phantoms - python-app
on: [push]
jobs:
  check-pygame:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.1' # Version range or exact version of a Python version to use, 

    - run: |
        python -m pip install --upgrade pip
        python3 -m pip install pygame==2.1.3.dev
